global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'go-app'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'redis'
    static_configs:
      - targets: ['notification_redis:9121']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
